const a=10;
const b=30
try {
   const sum= a/d
   console.log(sum);
} catch (error) {
    console.log('zeero err');
    
}finally{
    console.log('finsh');
